recaptcha and file size limit
OSLL/templater pull request #13
Opened 2020-09-05 23:08 UTC by levi218

resolved #12

2020-09-07 13:44 UTC, zmm requested changes
Синхронизировал ветку с мастером, развернул на http://templater.moevm.info/

Не увидел на странице капчи.
Также не уверен, что безопасно публиковать secret key в исходниках. Не могли бы вы создать еще одну пару ключей и сделать их передачу через build_and_run.sh?

2020-09-07 15:53 UTC, levi218 commented
![image](https://user-images.githubusercontent.com/31766219/92403230-ac0a2f80-f139-11ea-9b79-b03ef86dad01.png)

1. Отображается ли значок в правом нижнем углу страницы?
Oценка, которую возвращает recaptcha v3, обрабатывается на стороне сервера, если действие является подозрительным, сервер просто вернет ошибку, не обрабатывая ее.
Это нормально?
2. Ключ сайта (открытый ключ) находится в файле app / templater / static / js / main.js.
Закрытый ключ находится в файле конфигурации по адресу app / config.ini.
Итак, мне нужно переместить их в build_and_run.sh?
Ключ, который я ввел в исходный код, предназначен только для тестирования, я думаю, вам следует сгенерировать еще одну пару ключей recaptcha v3 перед развертыванием?

2020-09-07 16:17 UTC, levi218 commented
https://www.google.com/recaptcha/admin/create
сгенерируйте здесь пару ключей (recaptcha v3) и поместите их в файл build_and_run.sh

2020-09-08 16:43 UTC, zmm requested changes
Развернул с новым ключом, получаю такую ошибку в логах (страница не загружается)
Serving on http://0.0.0.0:5000
ERROR:waitress:Exception while serving /
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/view.py", line 779, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/waitress/channel.py", line 350, in service
    task.service()
  File "/usr/local/lib/python3.6/dist-packages/waitress/task.py", line 171, in service
    self.execute()
  File "/usr/local/lib/python3.6/dist-packages/waitress/task.py", line 441, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/paste/deploy/config.py", line 291, in __call__
    return self.app(environ, start_response)
  File "/app/templater/__init__.py", line 20, in m
  File "/usr/local/lib/python3.6/dist-packages/webob/request.py", line 1314, in send
    application, catch_exc_info=False)
  File "/usr/local/lib/python3.6/dist-packages/webob/request.py", line 1278, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/router.py", line 279, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/view.py", line 778, in invoke_exception_view
    reraise_(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/pyramid/router.py", line 277, in default_execution_policy
    return router.invoke_request(request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/usr/local/lib/python3.6/dist-packages/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/viewderivers.py", line 460, in rendered_view
    request, result, view_inst, context
  File "/usr/local/lib/python3.6/dist-packages/pyramid/renderers.py", line 451, in render_view
    return self.render_to_response(response, system, request=request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/renderers.py", line 474, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/renderers.py", line 470, in render
    result = renderer(value, system_values)
  File "/usr/local/lib/python3.6/dist-packages/pyramid_jinja2/__init__.py", line 264, in __call__
    template = self.template_loader()
  File "/usr/local/lib/python3.6/dist-packages/pyramid_jinja2/__init__.py", line 283, in template_loader
    return self.environment.get_template(name)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.6/dist-packages/pyramid_jinja2/__init__.py", line 250, in get_source
    raise TemplateNotFound(name=template, message=message)
jinja2.exceptions.TemplateNotFound: ../templates/homepage.jinja2; searchpath=['/app/templater']
ERROR:waitress:Exception while serving /favicon.ico
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/router.py", line 173, in handle_request
    raise HTTPNotFound(msg)
pyramid.httpexceptions.HTTPNotFound: /favicon.ico

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/waitress/channel.py", line 350, in service
    task.service()
  File "/usr/local/lib/python3.6/dist-packages/waitress/task.py", line 171, in service
    self.execute()
  File "/usr/local/lib/python3.6/dist-packages/waitress/task.py", line 441, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/paste/deploy/config.py", line 291, in __call__
    return self.app(environ, start_response)
  File "/app/templater/__init__.py", line 20, in m
  File "/usr/local/lib/python3.6/dist-packages/webob/request.py", line 1314, in send
    application, catch_exc_info=False)
  File "/usr/local/lib/python3.6/dist-packages/webob/request.py", line 1278, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/router.py", line 279, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/view.py", line 778, in invoke_exception_view
    reraise_(*exc_info)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/pyramid/router.py", line 277, in default_execution_policy
    return router.invoke_request(request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/view.py", line 767, in invoke_exception_view
    request_iface=request_iface.combined,
  File "/usr/local/lib/python3.6/dist-packages/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/viewderivers.py", line 460, in rendered_view
    request, result, view_inst, context
  File "/usr/local/lib/python3.6/dist-packages/pyramid/renderers.py", line 451, in render_view
    return self.render_to_response(response, system, request=request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/renderers.py", line 474, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/usr/local/lib/python3.6/dist-packages/pyramid/renderers.py", line 470, in render
    result = renderer(value, system_values)
  File "/usr/loc [...]

2020-09-10 07:19 UTC, zmm commented
@levi218 
Было две проблемы
- из-за инструкции ADD в докерфайле данные копировались в контейнер. Вместо этого создавалось что-то типа ссылки на них. А наш штатный механизм развертывания удаляет каталог с репозиторием, поэтому файлы терялись. ЗАмените, пожалуйста ADD на COPY
- подключение api.js проходило с захардкоженым ключом, заменил на шаблон

2020-09-10 07:20 UTC, merged